import { useMemo, useState } from 'react';
import { Bar, CartesianGrid, ComposedChart, Legend, Line, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { loadYankees, loadYankeesCareer } from './data';
import { QueryStatus, useMlbQuery } from './useMlbQuery';
import './yankees.css';

export type AcquisitionStats={war:number|null;games:number;avg?:number|null;ops?:number|null;era?:number|null;fip?:number|null;ip?:string;pa?:number};
export type AcquisitionYear={year:number;salary:number|null;payroll:number|null;payrollSource:string|null;payrollNotes:string|null;before:AcquisitionStats;nyy:AcquisitionStats;other:AcquisitionStats};
export type Acquisition={id:string;playerId:number;name:string;kind:'trade'|'fa';date:string;season:number;end:string;position:string;group:'hitting'|'pitching';age:number|null;returning:boolean;minor:boolean;description:string;from:string|null;hasMLB:boolean;missingProfile:boolean;before:AcquisitionStats;nyy:AcquisitionStats;pre3:number|null;preTrend:number|null;payrollTotal:number|null;missingPayrollYears:number[];payrollYears:number[];initialContract:{text:string;value:number;start:number;end:number}|null;guarantee:number|null;remainingAtAcquisition:number|null;remainingNow:number|null;financialNote:string;contractSource:string;source:string;statsSource:string;warSource:string};
export type YankeesDataset={asOf:string;coverage:{events:number;players:number;trades:number;freeAgents:number;missingProfiles:number;mlbEvents:number;payrollEvents:number};events:Acquisition[]};
const fmt=(n:number|null|undefined,d=1)=>n==null?'—':n.toFixed(d);
const dollars=(n:number|null|undefined)=>n==null?'Unknown':n===0?'$0':Math.abs(n)>=1e6?`$${(n/1e6).toFixed(2)}M`:`$${n.toLocaleString('en-US')}`;
const pair=(a:number|null|undefined,b:number|null|undefined,d=3)=>`${fmt(a,d)} → ${fmt(b,d)}`;
const statName=(r:Acquisition)=>r.group==='pitching'?'Pitching bWAR':'Batting bWAR';
function download(rows:Acquisition[]){
 const cols=['name','kind','date','age','position','before_war','nyy_war','before_avg','nyy_avg','before_ops','nyy_ops','before_era','nyy_era','before_fip','nyy_fip','before_ip','nyy_ip','known_payroll_estimate','assumed_guarantee','remaining_after_2026','missing_payroll_years','financial_note','transaction_source','contract_source'];
 const body=rows.map(r=>[r.name,r.kind,r.date,r.age,r.position,r.before.war,r.nyy.war,r.before.avg,r.nyy.avg,r.before.ops,r.nyy.ops,r.before.era,r.nyy.era,r.before.fip,r.nyy.fip,r.before.ip,r.nyy.ip,r.payrollTotal,r.remainingAtAcquisition,r.remainingNow,r.missingPayrollYears.join(';'),r.financialNote,r.source,r.contractSource]);
 const csv=[cols,...body].map(row=>row.map(x=>`"${String(x??'').replaceAll('"','""')}"`).join(',')).join('\r\n');
 const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8;'}));const a=document.createElement('a');a.href=url;a.download='yankees-acquisitions.csv';a.click();URL.revokeObjectURL(url);
}
function Career({player:r}:{player:Acquisition}){
 const q=useMlbQuery(`yankees-career:${r.id}`,()=>loadYankeesCareer(r.id));
 const [window,setWindow]=useState('career');
 const years=q.data??[];
 const plotted=years.filter(y=>(window==='career'||y.year>=r.season-3)&&((y.before.games>0||y.nyy.games>0)||y.payroll!=null||y.year<r.season)).map(y=>({year:y.year,before:y.year<=r.season&&(y.before.games>0||y.year<r.season)?y.before.war:null,nyy:y.year>=r.season&&(y.nyy.games>0||y.payroll!=null)?y.nyy.war:null,payroll:y.payroll==null?null:y.payroll/1e6}));
 return <section className="ya-detail" aria-label="Acquired player details">
  <div className="ya-player-heading"><div><p className="eyebrow">{r.kind==='trade'?'TRADE':'FREE AGENT'} · {r.date} · AGE {fmt(r.age)} · {r.position}</p><h3>{r.name}</h3><p>{r.description}</p></div><label>Chart history<select aria-label="Acquisition chart history" value={window} onChange={e=>setWindow(e.target.value)}><option value="career">Full MLB career</option><option value="recent">Three years before + Yankees years</option></select></label></div>
  <div className="ya-metrics">
   <div><span>Pre-acquisition {statName(r)}</span><strong className="ya-blue">{fmt(r.before.war)}</strong><small>All MLB teams before {r.date}</small></div>
   <div><span>Yankees {statName(r)}</span><strong className="ya-red">{fmt(r.nyy.war)}</strong><small>All later NYY seasons, including re-signings</small></div>
   <div><span>Known NYY payroll estimate</span><strong className="ya-gold">{dollars(r.payrollTotal)}</strong><small>{r.payrollYears.length} sourced years · {r.missingPayrollYears.length} playing years missing</small></div>
   <div><span>Assumed guarantee at acquisition</span><strong>{dollars(r.remainingAtAcquisition)}</strong><small>Remaining after 2026: {dollars(r.remainingNow)}</small></div>
  </div>
  <p className="ya-caption">Blue = before this acquisition. Red = Yankees performance after acquisition. Gold = sourced Yankees payroll estimate ($M). Other clubs’ later WAR is excluded. Missing money is never $0.</p>
  {q.loading||q.error?<QueryStatus error={q.error} retry={q.retry}/>:plotted.length?<div className="ya-chart" role="img" aria-label={`${r.name}: annual WAR before acquisition in blue, Yankees WAR in red, and Yankees payroll in gold. Exact values are in the annual table below.`}><ResponsiveContainer width="100%" height={340}><ComposedChart data={plotted} margin={{top:30,right:18,bottom:6,left:0}}>
   <CartesianGrid stroke="#303030" vertical={false}/><XAxis dataKey="year" tick={{fill:'#aaa',fontSize:11}}/><YAxis yAxisId="war" tick={{fill:'#aaa',fontSize:11}} label={{value:'bWAR',angle:-90,position:'insideLeft',fill:'#aaa'}}/><YAxis yAxisId="money" orientation="right" tick={{fill:'#d6b775',fontSize:11}} tickFormatter={n=>`$${n}M`} domain={[0,'auto']}/>
   <ReferenceLine yAxisId="war" y={0} stroke="#666"/><ReferenceLine yAxisId="war" x={r.season} stroke="#888" strokeDasharray="4 4" label={{value:'Acquisition season',position:'top',fill:'#bbb',fontSize:10}}/>
   <Tooltip contentStyle={{background:'#191919',border:'1px solid #444',borderRadius:6,color:'#eee'}} formatter={(v:number,name:string)=>[name==='NYY payroll estimate'?`$${v.toFixed(3)}M`:`${v.toFixed(2)} WAR`,name]} labelFormatter={v=>`Season ${v}`}/><Legend wrapperStyle={{fontSize:11,paddingTop:10}}/>
   <Bar isAnimationActive={false} yAxisId="war" dataKey="before" name="Before acquisition" fill="#64a8ed" maxBarSize={22}/><Bar isAnimationActive={false} yAxisId="war" dataKey="nyy" name="Yankees after acquisition" fill="#e0525b" maxBarSize={22}/><Line isAnimationActive={false} yAxisId="money" dataKey="payroll" name="NYY payroll estimate" stroke="#d6b775" strokeWidth={2} dot={{r:3}} connectNulls={false}/>
  </ComposedChart></ResponsiveContainer></div>:<div className="ya-empty">{r.missingProfile?'MLB profile could not be resolved. Statistics remain unknown.':'No MLB WAR or sourced Yankees payroll to plot for this acquisition.'}</div>}
  <div className="ya-stat-summary"><span>{r.group==='hitting'?`AVG ${pair(r.before.avg,r.nyy.avg)} · OPS ${pair(r.before.ops,r.nyy.ops)}`:`ERA ${pair(r.before.era,r.nyy.era,2)} · FIP ${pair(r.before.fip,r.nyy.fip,2)} · IP ${r.before.ip??'—'} → ${r.nyy.ip??'—'}`}</span><span>Last full season vs previous two: <strong>{r.preTrend==null?'Insufficient history':`${r.preTrend>0?'+':''}${fmt(r.preTrend)} WAR`}</strong></span></div>
  <p className="ya-financial-note">{r.financialNote} {r.missingPayrollYears.length>0&&`No sourced Yankees payroll for playing years ${r.missingPayrollYears.join(', ')}.`}</p>
  <div className="ya-source-links"><a href={r.source} target="_blank" rel="noreferrer">MLB transaction</a><a href={r.statsSource} target="_blank" rel="noreferrer">MLB statistics</a><a href={r.warSource} target="_blank" rel="noreferrer">Baseball Reference WAR / salaries</a><a href={r.contractSource} target="_blank" rel="noreferrer">Contract source</a></div>
  <details className="ya-annual"><summary>All annual salaries and performance ({years.length} seasons)</summary><p className="ya-caption">Reported annual salary is the Baseball Reference player-season figure across all employers, not the Yankees’ share. Payroll uses Cot’s salary plus allocated bonus estimates and listed offsets. Years without published salaries stay unknown. IP uses baseball notation: .1 = one out, .2 = two outs.</p><div className="ya-table-scroll"><table><thead><tr><th>Year</th><th>Before bWAR</th><th>NYY bWAR</th><th>{r.group==='hitting'?'AVG before → NYY':'ERA before → NYY'}</th><th>{r.group==='hitting'?'OPS before → NYY':'FIP before → NYY'}</th>{r.group==='pitching'&&<th>IP before → NYY</th>}<th>Reported salary, all clubs</th><th>NYY payroll estimate</th><th>Payroll source / notes</th></tr></thead><tbody>{years.map(y=><tr key={y.year}><td>{y.year}</td><td className="ya-blue">{y.before.games?fmt(y.before.war):'—'}</td><td className="ya-red">{y.nyy.games||y.payroll!=null?fmt(y.nyy.war):'—'}</td><td>{r.group==='hitting'?pair(y.before.avg,y.nyy.avg):pair(y.before.era,y.nyy.era,2)}</td><td>{r.group==='hitting'?pair(y.before.ops,y.nyy.ops):pair(y.before.fip,y.nyy.fip,2)}</td>{r.group==='pitching'&&<td>{y.before.ip} → {y.nyy.ip}</td>}<td>{dollars(y.salary)}</td><td>{dollars(y.payroll)}</td><td className="ya-note-cell">{y.payrollSource?<a href={y.payrollSource} target="_blank" rel="noreferrer">{y.payrollNotes||'Published payroll'}</a>:'No published allocation'}</td></tr>)}</tbody></table></div></details>
 </section>;
}
function AcquisitionTable({rows,title,selected,onSelect}:{rows:Acquisition[];title:string;selected:string;onSelect:(id:string)=>void}){
 const [limit,setLimit]=useState(30);
 return <section className="ya-cohort"><h3>{title}<span>{rows.length} records</span></h3><p className="ya-caption">Career before → Yankees after acquisition. Select a player for the annual chart, salaries and contract notes.</p><div className="ya-table-scroll"><table><thead><tr><th>Player / acquisition</th><th>Age</th><th>Before bWAR</th><th>NYY bWAR</th><th>Pre-acquisition trend¹</th><th>Known NYY payroll²</th><th>Assumed guarantee</th><th>Remaining after 2026</th><th>AVG</th><th>OPS</th><th>ERA</th><th>FIP³</th><th>IP</th></tr></thead><tbody>{rows.slice(0,limit).map(r=><tr key={r.id} className={selected===r.id?'ya-selected':''}><td><button className="ya-player-button" aria-pressed={selected===r.id} onClick={()=>onSelect(r.id)}>{r.name}</button><small>{r.date} · {r.position}{r.returning?' · Returning Yankee':''}{!r.hasMLB?' · No MLB stats':''}</small></td><td>{fmt(r.age)}</td><td className="ya-blue">{fmt(r.before.war)}</td><td className="ya-red">{fmt(r.nyy.war)}</td><td className={(r.preTrend??0)<0?'ya-red':''}>{r.preTrend==null?'—':`${r.preTrend>0?'+':''}${fmt(r.preTrend)}`}</td><td>{dollars(r.payrollTotal)}<small>{r.payrollYears.length} sourced years{r.missingPayrollYears.length?` · ${r.missingPayrollYears.length} missing`:''}</small></td><td>{dollars(r.remainingAtAcquisition)}</td><td>{dollars(r.remainingNow)}</td><td>{r.group==='hitting'?pair(r.before.avg,r.nyy.avg):'—'}</td><td>{r.group==='hitting'?pair(r.before.ops,r.nyy.ops):'—'}</td><td>{r.group==='pitching'?pair(r.before.era,r.nyy.era,2):'—'}</td><td>{r.group==='pitching'?pair(r.before.fip,r.nyy.fip,2):'—'}</td><td>{r.group==='pitching'?`${r.before.ip} → ${r.nyy.ip}`:'—'}</td></tr>)}</tbody></table></div>{!rows.length&&<p className="ya-empty">No acquisitions match these filters.</p>}{rows.length>limit&&<button className="ya-button" onClick={()=>setLimit(n=>n+50)}>Show 50 more ({rows.length-limit} remaining)</button>}</section>;
}
export default function YankeesAcquisitions(){
 const q=useMlbQuery('yankees-acquisitions',loadYankees);
 const [search,setSearch]=useState(''),[group,setGroup]=useState('all'),[sort,setSort]=useState('cost'),[scope,setScope]=useState('mlb'),[start,setStart]=useState('2009-11-01'),[repeats,setRepeats]=useState(false),[returning,setReturning]=useState(true),[selected,setSelected]=useState(''),[expensive,setExpensive]=useState(false),[zeroWar,setZeroWar]=useState(false),[declining,setDeclining]=useState(false);
 const events=q.data?.events??[];
 const filtered=useMemo(()=>{
  const seen=new Set<string>();
  return events.filter(r=>{
   if(r.date<start)return false;
   const key=`${r.kind}:${r.playerId}`;if(!repeats&&seen.has(key))return false;seen.add(key);
   return (!expensive||(r.payrollTotal!=null&&r.payrollTotal>=100_000_000))&&(!zeroWar||(r.nyy.war!=null&&r.nyy.war<=0))&&(!declining||(r.preTrend!=null&&r.preTrend<0))&&(scope==='all'||r.hasMLB)&&(returning||!r.returning)&&(group==='all'||r.group===group)&&`${r.name} ${r.description}`.toLowerCase().includes(search.toLowerCase());
  }).sort((a,b)=>sort==='name'?a.name.localeCompare(b.name):sort==='date'?b.date.localeCompare(a.date):sort==='war'?(b.nyy.war??-Infinity)-(a.nyy.war??-Infinity):sort==='lowwar'?(a.nyy.war??Infinity)-(b.nyy.war??Infinity):sort==='decline'?(a.preTrend??Infinity)-(b.preTrend??Infinity):(b.payrollTotal??-Infinity)-(a.payrollTotal??-Infinity));
 },[events,search,scope,group,sort,start,repeats,returning,expensive,zeroWar,declining]);
 const current=filtered.find(r=>r.id===selected)??filtered.find(r=>r.name==='Giancarlo Stanton')??filtered[0];
 const trades=filtered.filter(r=>r.kind==='trade'),fas=filtered.filter(r=>r.kind==='fa');
 const trend=filtered.filter(r=>r.preTrend!=null);
 if(q.loading||q.error)return <section className="ya"><QueryStatus error={q.error} retry={q.retry}/></section>;
 return <section className="ya" aria-label="Yankees acquisitions explorer">
  <div className="ya-heading"><div><p className="eyebrow">THE CASHMAN YEARS · 2010–2026</p><h2>What did the Yankees buy?</h2><p>Every recorded trade and free-agent signing. Compare the player they acquired with the performance and payroll that followed.</p></div><span className="ya-snapshot">Regular season · through {q.data?.asOf}</span></div>
  <div className="ya-filter-bar"><label>Find a player<input aria-label="Find acquired player" placeholder="Stanton, Ellsbury, Cole…" value={search} onChange={e=>setSearch(e.target.value)}/></label><label>Players<select aria-label="Acquisition player type" value={group} onChange={e=>setGroup(e.target.value)}><option value="all">Hitters + pitchers</option><option value="hitting">Hitters</option><option value="pitching">Pitchers</option></select></label><label>Sort both tables<select aria-label="Acquisition sort" value={sort} onChange={e=>setSort(e.target.value)}><option value="cost">Highest known NYY payroll</option><option value="lowwar">Lowest Yankees WAR</option><option value="war">Highest Yankees WAR</option><option value="decline">Largest pre-acquisition decline</option><option value="date">Newest acquisition</option><option value="name">Player name</option></select></label><label>Date range<select aria-label="Acquisition date range" value={start} onChange={e=>setStart(e.target.value)}><option value="2009-11-01">2010 season + offseason onward</option><option value="2010-01-01">January 1, 2010 onward</option></select></label><label>Coverage<select aria-label="Acquisition coverage" value={scope} onChange={e=>setScope(e.target.value)}><option value="mlb">Players with MLB career stats</option><option value="all">All, including prospects / no MLB stats</option></select></label></div>
  <div className="ya-options"><label><input type="checkbox" checked={returning} onChange={e=>setReturning(e.target.checked)}/>Include returning Yankees / re-signings</label><label><input type="checkbox" checked={repeats} onChange={e=>setRepeats(e.target.checked)}/>Show every acquisition event</label><button className="ya-button" onClick={()=>download(filtered)}>Download filtered CSV</button></div>
  <div className="ya-options ya-hypothesis" aria-label="Test acquisition hypothesis"><span>Test the hypothesis</span><label><input type="checkbox" checked={expensive} onChange={e=>setExpensive(e.target.checked)}/>≥ $100M known payroll</label><label><input type="checkbox" checked={zeroWar} onChange={e=>setZeroWar(e.target.checked)}/>≤ 0 Yankees WAR</label><label><input type="checkbox" checked={declining} onChange={e=>setDeclining(e.target.checked)}/>Lower WAR before acquisition¹</label></div><div className="ya-context"><span><strong>{trades.length}</strong> trade records</span><span><strong>{fas.length}</strong> free-agent records</span><span><strong>{filtered.filter(r=>r.payrollTotal!=null).length} / {filtered.length}</strong> with sourced payroll</span><span><strong>{trend.filter(r=>(r.preTrend??0)<0).length} / {trend.length}</strong> with lower WAR in final pre-acquisition season¹</span></div>
  <p className="ya-caution">Payroll is a known subtotal of published estimates, not audited cash paid. Unknown salary, cash offsets and contract balances remain unknown. A player can appear in both tables; overlapping acquisition records must not be added together.</p>
  {current&&<Career key={current.id} player={current}/>}
  <AcquisitionTable rows={trades} title="Trade acquisitions" selected={current?.id??''} onSelect={setSelected}/>
  <AcquisitionTable rows={fas} title="Free-agent signings" selected={current?.id??''} onSelect={setSelected}/>
  <details className="ya-method" open><summary>Definitions, coverage and limitations</summary><div>
   <p>¹ Pre-acquisition trend = WAR in the last complete season before the acquisition season, minus the average of the two preceding seasons. Negative means a decline in that comparison, not proof of a persistent decline. Requires three years since MLB debut. The shortened 2020 season is not annualized.</p>
   <p>² Known Yankees payroll sums sourced annual Cot’s estimates after acquisition, including subsequent contracts and listed payments after release, net of explicit cash offsets. Most older sheets are Opening Day snapshots, so midseason arrivals and final adjustments may be missing. Estimates include allocated signing bonuses. Zero-appearance years can still cost money. Ellsbury’s undisclosed settlement remains unknown. A blank means unknown, not zero. Remaining balances refer to guaranteed compensation after the 2026 season; unexercised options and arbitration projections are excluded.</p>
   <p>³ FIP is calculated from MLB counts: (13 × HR + 3 × (BB + HBP) − 2 × K) / IP + that season’s MLB constant, calibrated to MLB ERA. Multi-year FIP is innings-weighted. It is not park-adjusted. AVG, OPS and ERA are recomputed from totals, never averages of annual rates. IP counts outs.</p>
   <p>WAR is Baseball Reference bWAR throughout: position-player WAR for hitters and pitching WAR for pitchers. Before includes all MLB teams before the transaction, including earlier Yankees service. After includes only Yankees appearances from that acquisition onward, including later returns and re-signings. Other teams’ later WAR is excluded. Career totals span different lengths; use the annual chart to assess decline. Midseason rate stats use game logs. If a single team-season WAR row spans both sides of an acquisition, affected WAR is unknown rather than prorated.</p>
   <p>The ledger contains {q.data?.coverage.trades} trades and {q.data?.coverage.freeAgents} free-agent signing events ({q.data?.coverage.players} unique players) from November 2009 through {q.data?.asOf}. MLB transaction codes TR and SFA define membership; waiver claims, Rule 5 selections, draft picks and extensions without a free-agent transaction are outside these tables. Prospects and international/minor-league signings are available under “All.” Same-player/same-date/same-type duplicates are removed. Default tables show each player’s first acquisition by route within the selected date range. {q.data?.coverage.missingProfiles} transaction profiles could not be resolved; their statistics are unknown. Named PTBNL transactions are included when recorded; unnamed future considerations cannot be counted as identified players.</p>
   <p>Sources: <a href="https://statsapi.mlb.com/api/v1/transactions" target="_blank" rel="noreferrer">MLB Stats API</a>, <a href="https://www.baseball-reference.com/about/war_explained.shtml" target="_blank" rel="noreferrer">Baseball Reference</a>, and <a href="https://legacy.baseballprospectus.com/compensation/cots/al-east/new-york-yankees/" target="_blank" rel="noreferrer">Cot’s Baseball Contracts</a>. Player details link to specific evidence. This snapshot tests the expensive-decline hypothesis; it does not assume every acquisition failed.</p>
  </div></details>
 </section>;
}
