import { Download, Mail, Phone, MapPin } from 'lucide-react';
import resume from '../data/resume.json';

export default function ResumePage() {
  return <article className="resume-page">
    <div className="resume-topline"><p>Experience, technical skills, and education · September 2026</p><a className="portfolio-primary" href="/resume/scott-marshall-resume-september-2026.pdf" download="Scott-Marshall-Resume-September-2026.pdf"><Download size={17}/> Download PDF</a></div>
    <header className="resume-profile"><div><h2>{resume.name}</h2><p className="resume-role">{resume.roles[0].title}</p><span className="resume-clearance">{resume.clearance}</span></div><address><span><MapPin size={15}/><span>{resume.contact[0]}<br/>{resume.contact[1]}</span></span><a href="tel:+13367078552"><Phone size={15}/>{resume.contact[2]}</a><a href={`mailto:${resume.contact[3]}`}><Mail size={15}/>{resume.contact[3]}</a></address></header>
    <div className="resume-layout"><div><section aria-labelledby="resume-experience"><h2 id="resume-experience" className="resume-section-title">Experience</h2>{resume.roles.map(role => <section className="resume-job" key={role.title}><p className="resume-dates">{role.dates}</p><h3>{role.title}</h3><p className="resume-organization">{role.organization}</p>{role.paragraphs.map(text => <p key={text}>{text}</p>)}{role.bullets.length > 0 && <ul>{role.bullets.map(text => <li key={text}>{text}</li>)}</ul>}</section>)}</section><section className="resume-education" aria-labelledby="resume-education"><h2 id="resume-education" className="resume-section-title">Education</h2><h3>{resume.education[0]}</h3><p className="resume-dates">{resume.education[1]}</p>{resume.education.slice(2).map(text => <p key={text}>{text}</p>)}</section></div><aside><section aria-labelledby="resume-skills"><h2 id="resume-skills" className="resume-section-title">Skills</h2><ul>{resume.skills.map(skill => <li key={skill}>{skill}</li>)}</ul></section><section aria-labelledby="resume-tools"><h2 id="resume-tools" className="resume-section-title">Languages and tools</h2><ul>{resume.tools.map(tool => <li key={tool}>{tool}</li>)}</ul></section></aside></div>
    <div className="resume-download-footer"><p>Keep a copy of my resume.</p><a className="portfolio-primary" href="/resume/scott-marshall-resume-september-2026.pdf" download="Scott-Marshall-Resume-September-2026.pdf"><Download size={17}/> Download PDF</a></div>
  </article>;
}
